// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 31.5.2026, 21:46:03
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/dasdarki/Development/PnP/worldwright/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dasdarki/Development/PnP/worldwright/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dasdarki/Development/PnP/worldwright/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dasdarki/Development/PnP/worldwright/frontend/plugins/**/*.{js,ts,mjs}","/home/dasdarki/Development/PnP/worldwright/frontend/composables/**/*.{js,ts,mjs}","/home/dasdarki/Development/PnP/worldwright/frontend/utils/**/*.{js,ts,mjs}","/home/dasdarki/Development/PnP/worldwright/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dasdarki/Development/PnP/worldwright/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/dasdarki/Development/PnP/worldwright/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/dasdarki/Development/PnP/worldwright/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;